on: 
  workflow_dispatch:
  
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Go version
      uses: actions/setup-go@v2
      with:
        go-version: '1.24.4'
    - run: make unit_test